export type LucideModule = {
  default: any;
};

export type LucideModuleLoader = () => Promise<LucideModule>;

const iconModuleLoaders: Record<string, LucideModuleLoader> = {
  activity: () => import('lucide-svelte/icons/activity'),
  'alert-circle': () => import('lucide-svelte/icons/alert-circle'),
  'alert-triangle': () => import('lucide-svelte/icons/alert-triangle'),
  archive: () => import('lucide-svelte/icons/archive'),
  'arrow-down': () => import('lucide-svelte/icons/arrow-down'),
  'arrow-down-circle': () => import('lucide-svelte/icons/arrow-down-circle'),
  'arrow-left': () => import('lucide-svelte/icons/arrow-left'),
  'arrow-right': () => import('lucide-svelte/icons/arrow-right'),
  'arrow-up': () => import('lucide-svelte/icons/arrow-up'),
  'bar-chart-2': () => import('lucide-svelte/icons/bar-chart-2'),
  bell: () => import('lucide-svelte/icons/bell'),
  bold: () => import('lucide-svelte/icons/bold'),
  calendar: () => import('lucide-svelte/icons/calendar'),
  camera: () => import('lucide-svelte/icons/camera'),
  'check-circle': () => import('lucide-svelte/icons/check-circle'),
  chevron: () => import('lucide-svelte/icons/chevron-right'),
  'chevron-down': () => import('lucide-svelte/icons/chevron-down'),
  'chevron-left': () => import('lucide-svelte/icons/chevron-left'),
  'chevron-right': () => import('lucide-svelte/icons/chevron-right'),
  'chevron-up': () => import('lucide-svelte/icons/chevron-up'),
  'circle-alert': () => import('lucide-svelte/icons/circle-alert'),
  'circle-off': () => import('lucide-svelte/icons/circle-off'),
  'clipboard-list': () => import('lucide-svelte/icons/clipboard-list'),
  'clock-3': () => import('lucide-svelte/icons/clock-3'),
  cloud: () => import('lucide-svelte/icons/cloud'),
  copy: () => import('lucide-svelte/icons/copy'),
  cpu: () => import('lucide-svelte/icons/cpu'),
  'credit-card': () => import('lucide-svelte/icons/credit-card'),
  database: () => import('lucide-svelte/icons/database'),
  download: () => import('lucide-svelte/icons/download'),
  edit: () => import('lucide-svelte/icons/square-pen'),
  'square-pen': () => import('lucide-svelte/icons/square-pen'),
  'edit-3': () => import('lucide-svelte/icons/edit-3'),
  eraser: () => import('lucide-svelte/icons/eraser'),
  'external-link': () => import('lucide-svelte/icons/external-link'),
  eye: () => import('lucide-svelte/icons/eye'),
  'eye-off': () => import('lucide-svelte/icons/eye-off'),
  file: () => import('lucide-svelte/icons/file'),
  'file-plus': () => import('lucide-svelte/icons/file-plus'),
  'file-text': () => import('lucide-svelte/icons/file-text'),
  folder: () => import('lucide-svelte/icons/folder'),
  'folder-kanban': () => import('lucide-svelte/icons/folder-kanban'),
  'git-branch': () => import('lucide-svelte/icons/git-branch'),
  globe: () => import('lucide-svelte/icons/globe'),
  grid: () => import('lucide-svelte/icons/grid'),
  'hard-drive': () => import('lucide-svelte/icons/hard-drive'),
  'help-circle': () => import('lucide-svelte/icons/help-circle'),
  image: () => import('lucide-svelte/icons/image'),
  info: () => import('lucide-svelte/icons/info'),
  italic: () => import('lucide-svelte/icons/italic'),
  key: () => import('lucide-svelte/icons/key-round'),
  landmark: () => import('lucide-svelte/icons/landmark'),
  layers: () => import('lucide-svelte/icons/layers-3'),
  'life-buoy': () => import('lucide-svelte/icons/life-buoy'),
  link: () => import('lucide-svelte/icons/link-2'),
  list: () => import('lucide-svelte/icons/list'),
  'list-ordered': () => import('lucide-svelte/icons/list-ordered'),
  loader: () => import('lucide-svelte/icons/loader'),
  lock: () => import('lucide-svelte/icons/lock'),
  logout: () => import('lucide-svelte/icons/log-out'),
  mail: () => import('lucide-svelte/icons/mail'),
  map: () => import('lucide-svelte/icons/map'),
  'map-pin': () => import('lucide-svelte/icons/map-pin'),
  megaphone: () => import('lucide-svelte/icons/megaphone'),
  menu: () => import('lucide-svelte/icons/menu'),
  'message-circle': () => import('lucide-svelte/icons/message-circle'),
  minus: () => import('lucide-svelte/icons/minus'),
  monitor: () => import('lucide-svelte/icons/monitor'),
  moon: () => import('lucide-svelte/icons/moon'),
  music: () => import('lucide-svelte/icons/music'),
  package: () => import('lucide-svelte/icons/package'),
  paperclip: () => import('lucide-svelte/icons/paperclip'),
  pause: () => import('lucide-svelte/icons/pause'),
  'panel-right-close': () => import('lucide-svelte/icons/panel-right-close'),
  'panel-right-open': () => import('lucide-svelte/icons/panel-right-open'),
  play: () => import('lucide-svelte/icons/play'),
  plus: () => import('lucide-svelte/icons/plus'),
  'plus-circle': () => import('lucide-svelte/icons/plus-circle'),
  quote: () => import('lucide-svelte/icons/quote'),
  radio: () => import('lucide-svelte/icons/radio'),
  receipt: () => import('lucide-svelte/icons/receipt'),
  'refresh-cw': () => import('lucide-svelte/icons/refresh-cw'),
  'rotate-ccw': () => import('lucide-svelte/icons/rotate-ccw'),
  'rotate-cw': () => import('lucide-svelte/icons/rotate-cw'),
  rocket: () => import('lucide-svelte/icons/rocket'),
  router: () => import('lucide-svelte/icons/router'),
  satellite: () => import('lucide-svelte/icons/satellite'),
  save: () => import('lucide-svelte/icons/save'),
  search: () => import('lucide-svelte/icons/search'),
  send: () => import('lucide-svelte/icons/send'),
  server: () => import('lucide-svelte/icons/server'),
  settings: () => import('lucide-svelte/icons/settings'),
  shield: () => import('lucide-svelte/icons/shield'),
  'shield-alert': () => import('lucide-svelte/icons/shield-alert'),
  'shield-check': () => import('lucide-svelte/icons/shield-check'),
  'shield-off': () => import('lucide-svelte/icons/shield-off'),
  'shopping-cart': () => import('lucide-svelte/icons/shopping-cart'),
  smartphone: () => import('lucide-svelte/icons/smartphone'),
  star: () => import('lucide-svelte/icons/star'),
  sun: () => import('lucide-svelte/icons/sun'),
  trash: () => import('lucide-svelte/icons/trash-2'),
  'trash-2': () => import('lucide-svelte/icons/trash-2'),
  'trending-up': () => import('lucide-svelte/icons/trending-up'),
  underline: () => import('lucide-svelte/icons/underline'),
  upload: () => import('lucide-svelte/icons/upload'),
  user: () => import('lucide-svelte/icons/user'),
  'user-check': () => import('lucide-svelte/icons/user-check'),
  users: () => import('lucide-svelte/icons/users'),
  'wallet-cards': () => import('lucide-svelte/icons/wallet-cards'),
  wifi: () => import('lucide-svelte/icons/wifi'),
  'wifi-off': () => import('lucide-svelte/icons/wifi-off'),
  x: () => import('lucide-svelte/icons/x'),
  'x-circle': () => import('lucide-svelte/icons/circle-x'),
  zap: () => import('lucide-svelte/icons/zap'),
};

export function hasLucideIconModule(name: string): boolean {
  return name in iconModuleLoaders;
}

export function getLucideIconModuleLoader(name: string): LucideModuleLoader | undefined {
  return iconModuleLoaders[name];
}
